import { RoomRadio } from './radio.js';
import { ApartmentWorld } from './babylon-world.js?v=glbpaper3-20261005';
const canvas=document.querySelector('#world'),win=document.querySelector('#window'),body=document.querySelector('#window-body'),title=document.querySelector('#window-title');
const map=[
'11111111111111111111',
'10000000010000000001',
'10000000010000000001',
'10000000010000000001',
'10000000000000000001',
'10000000000000000001',
'10000000010000000001',
'11100011111110001111',
'10000000000000000001',
'10000001000000000001',
'10111101000010000001',
'10000001000010000001',
'10000001000010000001',
'10000000000000000001',
'11100011000001000111',
'10000001000001000001',
'10000001000001000001',
'10000001000001000001',
'10000001000001000001',
'11111111111111111111'];
const player={x:0,y:8.5,a:-Math.PI/2},keys={},found=new Set(),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const touch=matchMedia('(pointer:coarse)').matches,joy={x:0,y:0,id:null};
let world=null,last=0,dream=false,lace=true,sound=false,audio,started=false,near=null,drag=null,walk=0,showOutput=true;
const targets={home:{x:0,y:8.5,a:-Math.PI/2},wardrobe:{x:-7.4,y:-3.6,a:0},library:{x:7.4,y:-3,a:0},mirror:{x:7.4,y:2.1,a:0},radio:{x:7.4,y:-4.7,a:Math.PI},model:{x:0,y:2.4,a:-Math.PI/2},secret:{x:-8.1,y:-7,a:-Math.PI/2}};
const objects=[{x:-8.1,y:-5.8,key:'passage',name:'HIDDEN PASSAGE'},{x:0,y:0,key:'model',name:'CENTRAL PEARL'},{x:6.25,y:-4.7,key:'radio',name:'THE RADIO'},{x:-6.45,y:-2.35,key:'wardrobe',name:'THE WARDROBE'},{x:9,y:-3,key:'library',name:'THE ARCHIVE'},{x:9.3,y:2.1,key:'mirror',name:'THE MIRROR'},{x:-2.85,y:-8.25,key:'card',name:'READER’S CARD'},{x:-7.9,y:.8,key:'terminal',name:'THE COMPUTER'},{x:-7.6,y:-3.7,key:'thread0',name:'a loose thread'},{x:7.5,y:-2,key:'thread1',name:'another loose thread'},{x:7.4,y:3.8,key:'thread2',name:'the last loose thread'}];
try{world=new ApartmentWorld(canvas,map,objects,touch)}catch(error){console.error(error);dispatchEvent(new CustomEvent('dw-failed'));canvas.style.display='none';document.querySelector('#welcome h1').textContent='Explore the directory.';document.querySelector('.instructions').textContent='3D is unavailable in this browser. Rooms still opens every shelf.';document.querySelector('#begin').textContent='Apartment unavailable';document.querySelector('#begin').disabled=true}
addEventListener('resize',()=>world?.resize());addEventListener('orientationchange',()=>setTimeout(()=>world?.resize(),250));
function solid(x,y){if(x>=29&&x<33&&y>=8&&y<12)return false;return !map[Math.floor(y)]||map[Math.floor(y)][Math.floor(x)]!=='0'}
function canStand(x,y){return world?.ready&&!world.blocked(x,y)}
function move(dx,dy){if(canStand(player.x+dx,player.y))player.x+=dx;if(canStand(player.x,player.y+dy))player.y+=dy}
function begin(){if(world&&!world.ready&&!world.failed)return;started=true;document.querySelector('#welcome').classList.add('gone');document.body.classList.add('started')}
function say(text){document.querySelector('#whisper').textContent=text}
function log(text){const p=document.createElement('p');p.textContent=text;const el=document.querySelector('#log');el.append(p);while(el.children.length>20)el.firstElementChild.remove();el.scrollTop=el.scrollHeight}
function ping(freq=480){if(!sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='triangle';o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(freq/2,audio.currentTime+.3);g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.35);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+.36)}catch{log('Sound is unavailable in this browser.')}}
function travel(key){if(interactionTimer){clearTimeout(interactionTimer);interactionTimer=null}if(key==='secret'&&!puzzleSolved){say('Collect three threads and activate the central pearl to open the secret passage.');return false}const target=targets[key];if(!target)return false;resetMovement();Object.assign(player,target);begin();win.close();setTerminal(false);ping();say('Location: '+key);if(key==='secret'){dream=true;document.querySelector('#dream-toggle').setAttribute('aria-pressed','true')}log('location → '+key);return true}
function toggleDream(){win.close();setTerminal(false);dream=!dream;document.querySelector('#dream-toggle').setAttribute('aria-pressed',dream);begin();say(dream?'Dream on: the hidden wall in the textile room is highlighted.':'Dream off: normal lighting restored.');document.querySelector('#dream-toggle').innerHTML='<span>✳</span>Dream '+(dream?'on':'off');log('dream: '+(dream?'on':'off'));ping(220)}
function esc(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function getName(){try{return localStorage.getItem('opal-reader')||''}catch{return ''}}
const radio=new RoomRadio();let radioBusy=false;let zinePage=0;try{zinePage=Math.min(3,Math.max(0,parseInt(localStorage.getItem('opal-zine-page')||'0',10)||0))}catch{}
const panels={
rooms:['DIRECTORY','<h2>Directory</h2><p>Open a section here, or close this window to keep exploring.</p><div class="directory-files"><button class="room-choice" data-open="wardrobe"><span><em>Collections</em><small>Fashion archive placeholder</small></span><b>OPEN</b></button><button class="room-choice" data-open="library"><span><em>Library</em><small>Page viewer and saved reader card</small></span><b>OPEN</b></button><button class="room-choice" data-open="about"><span><em>About</em><small>Opal and the label</small></span><b>OPEN</b></button></div><div class="quick-commands"><button data-go="home">Entrance</button><button data-go="wardrobe">Textile room</button><button data-go="library">Archive</button></div>'],
wardrobe:['COLLECTIONS','<h2>Collections</h2><p>This section will display Dorothy Wolfe’s garments and collection photography. Product content has not been added to this demo.</p><button class="panel-action" data-open="shop">Shop preview</button>'],
shop:['SHOP PREVIEW','<h2>Shop</h2><p>Placeholder for products, sizes and purchasing links. Ordering is not enabled.</p>'],
library:['LIBRARY','<h2>Library</h2><p>A place for publications, journal entries and events.</p><button class="panel-action" data-open="zine">Open page viewer demo</button><button class="panel-action" data-open="card">Create a reader card</button>'],
mirror:['ABOUT / MIRROR','<h2>Dorothy Wolfe</h2><p>Dorothy Wolfe is Opal’s fashion label, named for her great-grandmother Dorothy and her own last name.</p><p>The mirror reflects your position as a floating sphere. Walk across it to see the reflection move.</p><button class="panel-action" id="dream-button">Toggle Dream mode</button>'],
about:['ABOUT','<h2>Dorothy Wolfe</h2><p>Dorothy Wolfe is Opal’s fashion label, named for her great-grandmother Dorothy and her own last name.</p>'],
help:['CONTROLS','<h2>How to explore</h2><p>One joystick: up and down walk, left and right turn. Push diagonally to do both. Tap the nearby-object prompt to interact. Tap ⇄ beside the joystick to move it to the other side.</p><p>Desktop: W/S walk, A/D or arrow keys turn, E interacts. Drag to turn. Escape closes a window.</p><p>Rooms opens content and room shortcuts. Terminal accepts commands. Dream changes the lighting and highlights the hidden passage.</p><p>Puzzle: collect three threads, activate the central pearl, then walk through the opened wall at the back of the textile room.</p><div class="help-list">goto wardrobe / library / mirror / home<br>dream — toggle lighting and reveal the seam<br>weave — toggle wallpaper<br>threads — puzzle progress<br>unravel — activate the collected threads<br>sound — toggle audio<br>clear — clear terminal</div>']};
const arrowLayer=document.querySelector('#room-arrows');
const roomSigns=[{key:'wardrobe',label:'Textile room',x:-5.12,z:-4.5},{key:'library',label:'Archive',x:5.12,z:-3.5},{key:'mirror',label:'Fitting room',x:5.12,z:4.1},{key:'atelier',label:'Atelier',x:-5.12,z:4.1},{key:'gallery',label:'Gallery',x:0,z:-5.62}];
targets.atelier={x:-7.4,y:3,a:-Math.PI/2};targets.gallery={x:0,y:-7,a:-Math.PI/2};
for(const sign of roomSigns){const button=document.createElement('button');button.className='room-arrow';button.dataset.go=sign.key;button.setAttribute('aria-label','Go to '+sign.label);button.innerHTML='<span class="floating-arrow" aria-hidden="true">↓</span><span class="room-arrow-label">'+sign.label+'</span>';button.hidden=true;arrowLayer.append(button);sign.button=button}
function updateRoomSigns(t){for(const sign of roomSigns){const point=started&&!interactionTimer&&!win.open&&!document.body.classList.contains('terminal-open')?world?.projectRoom?.(sign,player,t,reduced):null;sign.button.hidden=!point;if(point){sign.button.style.left=point.x+'%';sign.button.style.top=point.y+'%'}}}
function browseFirst(){started=true;document.querySelector('#welcome').classList.add('gone');document.body.classList.add('started');resetMovement();openPanel('rooms')}
document.querySelector('#browse-first').addEventListener('click',browseFirst);
function card(){return '<h2>Reader card</h2><p>A small personalization demo. Your name stays in this browser.</p><div class="card"><span>DOROTHY WOLFE</span><h3>Reader card</h3><div class="card-name">'+esc(getName()||'Visitor')+'</div></div><form id="card-form" class="name-form"><label for="reader">Your name</label><input id="reader" name="reader" maxlength="40" required value="'+esc(getName())+'"><button class="panel-action">Save card</button></form><p class="fine">No email or account needed.</p>'}
function openPanel(key){if(interactionTimer){clearTimeout(interactionTimer);interactionTimer=null}begin();if(key==='model'){title.textContent='APARTMENT / PUZZLE';body.innerHTML=modelPanel()}else if(key==='radio'){title.textContent='RADIO / CONTROLS';body.innerHTML=radioPanel()}else if(key==='zine'){title.textContent='ROOM NOTES / SAMPLE ISSUE 001';body.innerHTML=zinePanel()}else if(key==='card'){title.textContent='LIBRARY / READER’S CARD';body.innerHTML=card()}else if(panels[key]){title.textContent=panels[key][0];body.innerHTML=panels[key][1]}else return;resetMovement();setTerminal(false);document.querySelector('#window-path').textContent='dw:/'+(key==='rooms'?'directory':key);for(const sign of roomSigns)sign.button.hidden=true;if(!win.open)win.showModal();win.scrollTop=0;ping()}
let interactionTimer=null;
function interact(obj){if(interactionTimer)return;if(obj&&!obj.key.startsWith('thread')&&obj.key!=='return'&&world?.activate&&!reduced){resetMovement();world.activate(obj.key,performance.now());ping();interactionTimer=setTimeout(()=>{interactionTimer=null;finishInteraction(obj)},480);return}finishInteraction(obj)}
function finishInteraction(obj){if(!obj)return;if(obj.key==='model'){activatePearl();return}if(obj.key==='passage'){if(found.size<3){say('Collect all three threads, then activate the central pearl.');return}activatePearl();return}if(obj.key==='threshold'){travel('secret');return}if(obj.key==='return'){travel('model');return}if(obj.key==='terminal'){setTerminal(true);ping();return}if(obj.key.startsWith('thread')){if(found.has(obj.key))return;found.add(obj.key);document.querySelector('#thread-count').textContent=found.size+' / 3 FOUND';document.querySelector('#threads').textContent=Array.from({length:3},(_,i)=>i<found.size?'×':'·').join(' ');ping(800);say(found.size===3?'3 / 3 collected. Return to the central pearl to open the textile-room wall.':found.size+' / 3 threads collected. Find the remaining glowing loops.');log(found.size===3?'3 threads found. New command: unravel.':'thread collected ('+found.size+'/3)');near=null}else openPanel(obj.key)}
function run(raw){const cmd=raw.trim().toLowerCase();log('visitor:~$ '+raw);if(cmd.startsWith('goto ')){if(!travel(cmd.slice(5)))log('No such room. Try wardrobe, library, mirror, or home.')}else if(cmd==='dream')toggleDream();else if(cmd==='weave'){lace=!lace;begin();log(lace?'Wallpaper on.':'Wallpaper off.');say(lace?'Wallpaper on.':'Wallpaper off.')}else if(cmd==='unravel'){if(found.size<3)log('Find all three threads first. Try “threads”.');else{activatePearl()}}else if(cmd==='threads')log(found.size+'/3 found. Look near the wardrobe, library, and mirror.');else if(cmd==='look')log(near?'Within reach: '+near.name+'. Press E.':'No object within reach. Walk closer and face an object.');else if(cmd==='home')travel('home');else if(cmd==='terminal')setTerminal(true);else if(cmd==='sound')document.querySelector('#sound').click();else if(cmd==='clear')document.querySelector('#log').replaceChildren();else if(cmd==='model'||cmd==='map'||cmd==='radio'||cmd==='zine'||cmd==='card'||panels[cmd])openPanel(cmd==='map'?'model':cmd);else if(cmd==='hello'||cmd==='hi'){say('Hello, '+(getName()||'stranger')+'.');log('Type help for available commands.')}else log('Unknown command. Type help.')}
let lastInteractionCheck=-Infinity;
const ui={interact:document.querySelector('#interact'),coords:document.querySelector('#coords'),location:document.querySelector('#location'),hud:document.querySelector('#hud-target')};const shown=new Map();function put(el,v){if(el&&shown.get(el)!==v){shown.set(el,v);el.textContent=v}}
function render(t){updateRoomSigns(t);radio.update(player,sound,document.hidden);if(world){world.render(player,found,dream,lace,t,reduced);if(t-lastInteractionCheck>100){near=world.nearest(player,found);lastInteractionCheck=t}}else near=null;const button=ui.interact,hide=!near||win.open||!started||!!interactionTimer;if(button.hidden!==hide)button.hidden=hide;if(near)put(button,(touch?'Touch · ':'[ E ] ')+(near.key.startsWith('thread')?'pull this thread':near.name.toLowerCase()));put(ui.hud,near?'[ '+near.name.toUpperCase()+' ]  /  '+(touch?'TOUCH TO OPEN':'PRESS E'):'LOOK FOR SOMETHING TO TOUCH');if(!touch)put(ui.coords,'x '+player.x.toFixed(2)+' / y '+player.y.toFixed(2));put(ui.location,player.y>5.8?'VESTIBULE':player.y<-5.8&&player.x<-1.97?'BEDROOM ALCOVE':player.y<-5.8?'GALLERY':player.x<-5.3?(player.y<-1.6?'TEXTILE ROOM':'ATELIER'):player.x>5.3?(player.y<-.1?'ARCHIVE':'FITTING ROOM'):Math.abs(player.x)<3.1&&Math.abs(player.y)<3.6?'UNDER THE STARS':'THE PASSAGE');}
let lastPaint=0,frameGap=touch?14:0,slowFrames=0;
function stepMovement(dt){const f=(keys.w||keys.arrowup?1:0)-(keys.s||keys.arrowdown?1:0)-joy.y,turn=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0)+joy.x;if(!f&&!turn)return;begin();player.a+=Math.max(-1,Math.min(1,turn))*dt*1.65;const speed=(touch?2.15:2.6)*dt*Math.max(-1,Math.min(1,f));move(Math.cos(player.a)*speed,Math.sin(player.a)*speed)}
function loop(t){if(document.hidden){last=t;requestAnimationFrame(loop);return}const dt=Math.min(.04,(t-last)/1000||0);last=t;if(!interactionTimer&&!win.open&&document.activeElement.tagName!=='INPUT'&&!document.body.classList.contains('terminal-open'))stepMovement(dt);if(t-lastPaint>=frameGap&&!win.open){const gap=t-lastPaint;render(t);lastPaint=t;if(touch&&frameGap<30&&started){slowFrames=gap>26&&gap<200?slowFrames+1:Math.max(0,slowFrames-1);if(slowFrames>45)frameGap=31}}requestAnimationFrame(loop)}requestAnimationFrame(loop);
addEventListener('keydown',e=>{if(document.activeElement.tagName==='INPUT'||win.open||document.body.classList.contains('terminal-open'))return;const k=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright','e'].includes(k)){e.preventDefault();keys[k]=true;if(k==='e'&&!e.repeat)interact(near)}});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);addEventListener('blur',resetMovement);document.addEventListener('visibilitychange',()=>{if(document.hidden)resetMovement()});
canvas.addEventListener('pointerdown',e=>{if(drag)return;drag={id:e.pointerId,x:e.clientX,start:e.clientX,y:e.clientY,moved:false};canvas.setPointerCapture(e.pointerId)});
canvas.addEventListener('pointermove',e=>{if(!touch&&drag&&e.pointerId===drag.id&&!win.open){player.a+=(e.clientX-drag.x)*(touch?.0045:.006);if(Math.abs(e.clientX-drag.start)>5||Math.abs(e.clientY-drag.y)>5)drag.moved=true;drag.x=e.clientX;if(drag.moved)begin()}});
canvas.addEventListener('pointerup',e=>{if(!drag||drag.id!==e.pointerId)return;if(!drag.moved){const hit=world?.hitAt(e.clientX,e.clientY);if(hit)interact(hit);else begin()}drag=null});canvas.addEventListener('pointercancel',()=>drag=null);canvas.addEventListener('lostpointercapture',()=>drag=null);
const joystick=document.querySelector('#joystick'),stick=document.querySelector('#stick');
// Joystick side: right by default, ⇄ flips it, choice remembered in this browser.
function setHand(side){document.body.classList.toggle('hand-left',side==='left');try{localStorage.setItem('dw-hand',side)}catch{}}
{let saved='right';try{saved=localStorage.getItem('dw-hand')||'right'}catch{}setHand(saved)}
document.querySelector('#swap-hand').addEventListener('click',()=>{resetMovement();setHand(document.body.classList.contains('hand-left')?'right':'left');ping(520)});
function setJoy(x,y){const length=Math.hypot(x,y),radius=38,scale=length>radius?radius/length:1;let dx=x*scale,dy=y*scale;const axis=v=>Math.abs(v)<6?0:Math.sign(v)*(Math.abs(v)-6)/(radius-6);joy.x=axis(dx);joy.y=axis(dy);stick.style.transform='translate('+dx+'px,'+dy+'px)'}
function resetMovement(){Object.keys(keys).forEach(k=>keys[k]=false);joy.id=null;joy.x=joy.y=0;drag=null;const s=document.querySelector('#stick');if(s)s.style.transform='translate(0px,0px)'}
function updateJoy(e){const r=joystick.querySelector('.joystick-ring').getBoundingClientRect();setJoy(e.clientX-r.left-r.width/2,e.clientY-r.top-r.height/2)}
joystick.addEventListener('pointerdown',e=>{e.preventDefault();if(joy.id!==null)return;joy.id=e.pointerId;joystick.setPointerCapture(e.pointerId);begin();updateJoy(e)});joystick.addEventListener('pointermove',e=>{if(e.pointerId===joy.id){e.preventDefault();updateJoy(e)}});for(const event of ['pointerup','pointercancel','lostpointercapture'])joystick.addEventListener(event,e=>{if(e.pointerId===joy.id){joy.id=null;setJoy(0,0)}});
function setTerminal(open){resetMovement();document.querySelector('#console').hidden=!open;document.querySelector('#terminal-toggle').setAttribute('aria-expanded',open);document.body.classList.toggle('terminal-open',open);if(!open)document.querySelector('#command').blur();begin()}
document.querySelector('#terminal-toggle').onclick=()=>setTerminal(document.querySelector('#console').hidden);document.querySelector('#dream-toggle').onclick=toggleDream;
function keyboardViewport(){const v=window.visualViewport,k=v?Math.max(0,innerHeight-v.height-v.offsetTop):0;document.documentElement.style.setProperty('--keyboard',k+'px');document.body.classList.toggle('keyboard-open',k>100)}if(window.visualViewport){window.visualViewport.addEventListener('resize',keyboardViewport);window.visualViewport.addEventListener('scroll',keyboardViewport)}
document.addEventListener('click',e=>{const go=e.target.closest('[data-go]'),open=e.target.closest('[data-open]');const command=e.target.closest('[data-command]');if(command)run(command.dataset.command);if(go)travel(go.dataset.go);if(open)openPanel(open.dataset.open);if(e.target.closest('#dream-button')){win.close();toggleDream()}});
document.querySelector('#begin').onclick=()=>world&&!world.failed?begin():browseFirst();document.querySelector('#interact').onclick=()=>interact(near);document.querySelector('#home').onclick=e=>{e.preventDefault();travel('home')};document.querySelector('#close').onclick=()=>win.close();
win.addEventListener('click',e=>{if(e.target===win){const r=win.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)win.close()}});
document.querySelector('#terminal').onsubmit=e=>{e.preventDefault();const input=document.querySelector('#command');if(input.value.trim())run(input.value);input.value='';input.blur()};
function setSound(value){sound=value;const b=document.querySelector('#sound');b.textContent='sound: '+(sound?'on':'off');b.setAttribute('aria-pressed',sound);radio.update(player,sound,document.hidden)}
document.querySelector('#sound').onclick=()=>{setSound(!sound);if(sound&&radio.ctx)radio.ctx.resume().catch(()=>{});ping()};
document.querySelector('#console-toggle').onclick=()=>setTerminal(false);
document.addEventListener('submit',e=>{if(e.target.id!=='card-form')return;e.preventDefault();const name=new FormData(e.target).get('reader').trim();if(!name)return;try{localStorage.setItem('opal-reader',name);openPanel('card');body.querySelector('.fine').textContent='Name saved in this browser.'}catch{body.querySelector('.card-name').textContent=name;body.querySelector('.fine').textContent='Your card is ready for this visit. This browser could not save it.'}});

const pages=[
'<h2>Page viewer</h2><p>This four-page demo can hold a zine, lookbook or collection story. Use the buttons below to turn pages.</p>',
'<h2>Images & text</h2><p>Each page can combine photographs, captions and longer writing. Final editorial content will be added later.</p>',
'<h2>Reading progress</h2><p>The viewer remembers your last page in this browser. Desktop readers can also use the left and right arrow keys.</p>',
'<h2>Reader card</h2><p>The reader card demonstrates local personalization.</p><button class="panel-action" data-open="card">Create a card</button>'
];
function zinePanel(){return '<article class="zine-page" aria-label="Page '+(zinePage+1)+' of 4">'+pages[zinePage]+'</article><nav class="zine-controls" aria-label="Zine pages"><button data-page="-1" '+(zinePage===0?'disabled':'')+'>← Previous</button><span aria-live="polite">'+(zinePage+1)+' / 4</span><button data-page="1" '+(zinePage===3?'disabled':'')+'>Next →</button></nav><p class="fine">Demo content. Your page is remembered in this browser.</p>'}
function turnPage(delta){zinePage=Math.max(0,Math.min(3,zinePage+delta));try{localStorage.setItem('opal-zine-page',String(zinePage))}catch{}body.innerHTML=zinePanel();win.scrollTop=0;ping(560)}
function radioPanel(){return '<p class="eyebrow">AUDIO CONTROLS</p><h2>Radio</h2><div class="radio-dial"><span>88</span><span>96</span><span>104</span><span>108</span></div><p id="radio-state" role="status">'+(radio.playing?'Playing':'Off')+' · '+(radio.station===0?'01 / Audio sketch 01':'02 / Audio sketch 02')+'</p><button class="panel-action" id="radio-power">'+(radio.playing?'Switch off':'Switch on')+'</button><div class="radio-stations"><button data-station="0" aria-pressed="'+(radio.station===0)+'">01 · Audio sketch 01</button><button data-station="1" aria-pressed="'+(radio.station===1)+'">02 · Audio sketch 02</button></div><label class="radio-volume" for="radio-volume">Volume <input id="radio-volume" type="range" min="0" max="100" value="'+Math.round(radio.volume*100)+'"></label><p>The radio stays here. Walk closer to listen; wander away and it fades.</p><button class="panel-action" data-go="radio">Find the radio ↗</button><p class="fine">Temporary synthesized audio. Final music has not been added yet. The top sound button mutes everything.</p>'}
document.addEventListener('click',async e=>{const p=e.target.closest('[data-page]'),station=e.target.closest('[data-station]');if(p)turnPage(Number(p.dataset.page));if(station){radio.tune(Number(station.dataset.station));body.innerHTML=radioPanel()}if(e.target.closest('#radio-power')&&!radioBusy){radioBusy=true;try{await radio.toggle();if(radio.playing)setSound(true);if(win.open&&title.textContent.startsWith('RADIO'))body.innerHTML=radioPanel()}catch(error){const el=document.querySelector('#radio-state');if(el)el.textContent=error.message}finally{radioBusy=false}}});
document.addEventListener('input',e=>{if(e.target.id==='radio-volume'){radio.volume=Number(e.target.value)/100;radio.update(player,sound,document.hidden)}});
win.addEventListener('keydown',e=>{if(title.textContent.startsWith('ROOM NOTES')&&!['INPUT','TEXTAREA'].includes(e.target.tagName)&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();turnPage(e.key==='ArrowRight'?1:-1)}});
document.addEventListener('visibilitychange',()=>radio.update(player,sound,document.hidden));

let puzzleSolved=false;
function activatePearl(){
 if(found.size<3){if(!dream)toggleDream();say(found.size+' / 3 threads collected. Find the loops in the textile room, archive and fitting room.');return}
 if(puzzleSolved){say('Passage already open. Find it at the back of the textile room.');return}
 win.close();setTerminal(false);dream=true;document.querySelector('#dream-toggle').setAttribute('aria-pressed','true');document.querySelector('#dream-toggle').innerHTML='<span>✳</span>Dream on';puzzleSolved=true;world?.openPassage(performance.now());ping(160);say('Passage opened! The wall at the back of the textile room has lifted.');log('Puzzle complete: textile room → gallery shortcut open.');document.querySelector('#thread-count').textContent='PASSAGE OPEN';
}
function modelPanel(){return '<h2>Apartment puzzle</h2><p>'+ (puzzleSolved?'Complete. The textile-room wall is raised, opening a shortcut through the gallery wall.':found.size===3?'All three threads collected. Activate the central pearl to raise the hidden wall.':found.size+' / 3 threads collected. Find the glowing loops in the textile room, archive and fitting room. Then return to the central pearl.')+'</p><button class="panel-action" data-go="'+(puzzleSolved?'wardrobe':'model')+'">'+(puzzleSolved?'Go to textile room':'Go to central pearl')+'</button><p class="fine">Dream mode changes the sky and lighting and highlights the hidden wall. Opening Collections does not activate the puzzle.</p>'}
