import { Reflector } from './vendor/objects/Reflector.js';
import * as THREE from './vendor/three.module.js';
const boxGeometry=new THREE.BoxGeometry(1,1,1);
const mat=(color,extra={})=>new THREE.MeshLambertMaterial({color,flatShading:true,...extra});
function box(group,x,y,z,w,h,d,material){const m=new THREE.Mesh(boxGeometry,material);m.position.set(x,y,z);m.scale.set(w,h,d);group.add(m);return m}
function screenTexture(lines){const c=document.createElement('canvas');c.width=256;c.height=192;const g=c.getContext('2d');g.fillStyle='#180f1d';g.fillRect(0,0,256,192);g.fillStyle='#ffb7d5';g.font='16px monospace';lines.forEach((line,i)=>g.fillText(line,16,32+i*27));g.fillRect(16,159,10,15);const t=new THREE.CanvasTexture(c);t.magFilter=THREE.NearestFilter;t.minFilter=THREE.NearestFilter;t.colorSpace=THREE.SRGBColorSpace;return t}
export function buildApartment(map,objects,textures={}){
 const scene=new THREE.Scene();scene.background=new THREE.Color('#1e122c');scene.fog=new THREE.Fog('#1e122c',12,32);
 scene.add(new THREE.HemisphereLight('#fff4fa','#b693a8',2.1));const sun=new THREE.DirectionalLight('#fff1f5',1.25);sun.position.set(4,9,7);scene.add(sun);
 const wallpaper=mat('#fff0f7',{map:textures.wallpaper||null}),paint=mat('#edc5da'),skirt=mat('#9e6e88'),trim=mat('#fff1f8');
 const cells=[];for(let z=0;z<map.length;z++)for(let x=0;x<map[z].length;x++)if(map[z][x]==='1')cells.push([x+.5,z+.5]);
 const matrix=new THREE.Matrix4(),wallMeshes=[];
 for(const [material,y,height]of [[wallpaper,1.44,1.28],[paint,.465,.67],[skirt,.065,.13],[trim,2.115,.07]]){const mesh=new THREE.InstancedMesh(boxGeometry,material,cells.length);cells.forEach(([x,z],i)=>{matrix.compose(new THREE.Vector3(x,y,z),new THREE.Quaternion(),new THREE.Vector3(1,height,1));mesh.setMatrixAt(i,matrix)});mesh.instanceMatrix.needsUpdate=true;scene.add(mesh);wallMeshes.push(mesh)}
 const floor=new THREE.Mesh(new THREE.PlaneGeometry(20,20),mat('#ffeaf4',{map:textures.parquet||null,emissive:'#9a6882',emissiveIntensity:.20}));floor.rotation.x=-Math.PI/2;floor.position.set(10,-.005,10);scene.add(floor);
 const gray=mat('#d8c2d1'),light=mat('#f5d9e8'),dark=mat('#69475e'),wood=mat('#a27a8d'),pink=mat('#f3a5ce'),black=mat('#160e1c'),metal=mat('#9b859b');
 const props=new Map(),colliders=[],threadMeshes=[];let mirrorSurface=null,reflectionRibbon=null,miniMarker=null,passagePanel=null,passageSeam=null;const mechanisms=new Map();
 function table(g){box(g,0,.76,0,1.55,.12,.86,wood);for(const x of [-.65,.65])for(const z of [-.32,.32])box(g,x,.36,z,.1,.72,.1,dark)}
 function chair(parent,x,z,rotation=0){const g=new THREE.Group();g.position.set(x,0,z);g.rotation.y=rotation;parent.add(g);box(g,0,.45,0,.48,.10,.47,gray);box(g,0,.81,-.20,.48,.67,.075,gray);for(const a of [-.18,.18])for(const b of [-.17,.17])box(g,a,.22,b,.055,.44,.055,dark)}
 for(const o of objects){const g=new THREE.Group();g.position.set(o.x,0,o.y);g.userData.key=o.key;g.userData.object=o;scene.add(g);props.set(o.key,g);let rx=.75,rz=.45,focusY=1.1;
  if(o.key==='terminal'){table(g);box(g,0,1.14,-.09,.75,.65,.53,gray);box(g,0,1.14,.187,.66,.52,.025,dark);const display=new THREE.Mesh(new THREE.PlaneGeometry(.57,.42),new THREE.MeshBasicMaterial({map:screenTexture(['DOROTHY WOLFE','APARTMENT 04','> HELLO, VISITOR','> OPEN TERMINAL']),toneMapped:false}));display.position.set(0,1.14,.204);g.add(display);mechanisms.set(o.key,{type:'screen',material:display.material});box(g,0,.83,.26,.7,.045,.22,light);for(let n=0;n<9;n++)box(g,-.28+n*.07,.859,.25,.048,.012,.12,dark);box(g,.28,.94,.19,.06,.06,.03,pink);chair(g,1.12,.25,-.5);colliders.push({x:o.x+1.12,z:o.y+.25,rx:.3,rz:.3,key:o.key});}
  else if(o.key==='radio'){rx=.45;rz=.3;focusY=.91;box(g,0,.3,0,.62,.6,.45,wood);box(g,0,.87,0,.83,.5,.36,light);box(g,-.17,.87,.19,.38,.34,.025,dark);for(let i=0;i<7;i++)box(g,-.31+i*.05,.87,.21,.016,.30,.018,gray);box(g,.23,.98,.20,.23,.055,.026,pink);for(const y of [.79,.9]){const knob=new THREE.Mesh(new THREE.CylinderGeometry(.045,.045,.03,8),dark);knob.rotation.x=Math.PI/2;knob.position.set(.25,y,.22);g.add(knob);if(y===.9)mechanisms.set(o.key,{type:'dial',mesh:knob})}box(g,.26,1.35,-.07,.02,.5,.02,metal);}
  else if(o.key==='wardrobe'){box(g,0,1.1,-.29,1.5,2.2,.08,wood);box(g,-.71,1.1,0,.08,2.2,.65,wood);box(g,.71,1.1,0,.08,2.2,.65,wood);box(g,0,.13,0,1.5,.12,.65,dark);const doors=[];for(const side of [-1,1]){const hinge=new THREE.Group();hinge.position.set(side*.73,0,.35);g.add(hinge);box(hinge,-side*.35,1.13,0,.70,2.05,.055,gray);box(hinge,-side*.35,1.15,.035,.59,1.85,.016,light);box(hinge,-side*.63,1.15,.08,.045,.22,.065,dark);doors.push({hinge,side})}box(g,0,2.24,0,1.61,.09,.76,dark);box(g,0,1.8,0,1.3,.04,.04,metal);for(let i=0;i<3;i++)box(g,-.36+i*.36,1.1,-.06,.25,1.1,.06,i%2?pink:light);mechanisms.set(o.key,{type:'doors',doors});rx=.83;rz=.43;focusY=1.3;}
  else if(o.key==='library'){focusY=.85;table(g);for(let i=0;i<3;i++){const book=box(g,-.36+i*.34,.85+i*.015,.08,.29,.055,.4,i%2?pink:light);book.rotation.y=(i-1)*.17;if(i===1)mechanisms.set(o.key,{type:'book',mesh:book,baseY:book.position.y})}chair(g,1.08,.12,-.7);colliders.push({x:o.x+1.08,z:o.y+.12,rx:.3,rz:.3,key:o.key},{x:o.x+1.75,z:o.y-.65,rx:.56,rz:.5,key:o.key});const shelf=new THREE.Group();shelf.position.set(1.75,0,-.65);g.add(shelf);box(shelf,0,1,0,1,2,.3,dark);for(const y of [.25,.8,1.35,1.9]){box(shelf,0,y,.20,1.08,.07,.5,gray);if(y<1.8)for(let i=0;i<5;i++)box(shelf,-.36+i*.18,y+.21,.15,.12,.36,.24,i%2?wood:light)} }
  else if(o.key==='mirror'){g.rotation.y=Math.PI;box(g,0,1.24,0,1.03,2.05,.14,dark);box(g,0,1.24,.085,.88,1.87,.04,metal);mirrorSurface=new Reflector(new THREE.PlaneGeometry(.77,1.75),{color:0xe4c6d8,textureWidth:textures.lowPower?128:384,textureHeight:textures.lowPower?256:512,clipBias:.003,multisample:0});const drawReflection=mirrorSurface.onBeforeRender;let lastReflection=-Infinity;mirrorSurface.onBeforeRender=function(...args){const now=performance.now();if(textures.lowPower&&now-lastReflection<100)return;lastReflection=now;drawReflection.apply(this,args)};mirrorSurface.getRenderTarget().texture.type=THREE.UnsignedByteType;mirrorSurface.position.set(0,1.24,.13);mirrorSurface.camera.layers.enable(1);g.add(mirrorSurface);box(g,0,.12,0,1.15,.22,.45,wood);rx=.6;rz=.28;focusY=1.35;
   reflectionRibbon=null;

  }
  else if(o.key==='passage'){rx=.50;rz=1;focusY=1.1;passagePanel=new THREE.Group();g.add(passagePanel);box(passagePanel,0,1.44,0,1,1.28,2,wallpaper);box(passagePanel,0,.465,0,1,.67,2,paint);box(passagePanel,0,.065,0,1,.13,2,skirt);passageSeam=new THREE.Group();passagePanel.add(passageSeam);const glow=new THREE.MeshBasicMaterial({color:'#ffd2ec'});box(passageSeam,.51,1.1,-.92,.02,1.8,.018,glow);box(passageSeam,.51,1.1,.92,.02,1.8,.018,glow);box(passageSeam,.51,1.99,0,.02,.018,1.86,glow);passageSeam.visible=false;}
  else if(o.key==='threshold'){rx=.6;rz=.2;focusY=1.1;box(g,-.55,1.05,0,.10,2.1,.18,pink);box(g,.55,1.05,0,.10,2.1,.18,pink);box(g,0,2.05,0,1.2,.1,.18,light);const face=new THREE.Mesh(new THREE.PlaneGeometry(.98,1.9),new THREE.MeshBasicMaterial({color:'#130e25'}));face.position.set(0,1.04,.1);g.add(face);for(let i=0;i<7;i++)box(g,Math.sin(i*2.4)*.3,.4+i*.19,.12,.018,.018,.018,new THREE.MeshBasicMaterial({color:'#ffe1f0'}));}
  else if(o.key==='return'){rx=.6;rz=.18;focusY=1.1;box(g,0,-.055,1.2,4,.10,4,light).userData.skipInteraction=true;box(g,-.55,1.05,0,.12,2.1,.22,pink);box(g,.55,1.05,0,.12,2.1,.22,pink);box(g,0,2.05,0,1.2,.12,.22,pink);const face=new THREE.Mesh(new THREE.PlaneGeometry(.96,1.9),new THREE.MeshBasicMaterial({map:screenTexture(['THE ROOM','INSIDE THE ROOM','','> RETURN'])}));face.position.set(0,1.04,.13);g.add(face);}
  else if(o.key==='model'){rx=1.05;rz=.86;focusY=1.0;box(g,0,.76,0,2.1,.14,1.7,wood);for(const x of [-.88,.88])for(const z of [-.68,.68])box(g,x,.36,z,.12,.72,.12,dark);box(g,0,.87,0,1.35,.08,1.35,dark);const modelWalls=new THREE.InstancedMesh(boxGeometry,light,cells.length);const m=new THREE.Matrix4();cells.forEach(([x,z],i)=>{m.compose(new THREE.Vector3((x-10)*.062,.98,(z-10)*.062),new THREE.Quaternion(),new THREE.Vector3(.061,.15,.061));modelWalls.setMatrixAt(i,m)});g.add(modelWalls);mechanisms.set(o.key,{type:'model',mesh:modelWalls});miniMarker=new THREE.Mesh(new THREE.ConeGeometry(.03,.07,4),new THREE.MeshBasicMaterial({color:'#ff69b4'}));miniMarker.position.set(0,1.12,0);g.add(miniMarker);for(let i=0;i<3;i++)box(g,-.35+i*.35,.88,.74,.18,.06,.12,pink);}
  else if(o.key==='card'){focusY=.85;table(g);box(g,0,.855,.1,.48,.025,.32,pink);const card=new THREE.Mesh(new THREE.PlaneGeometry(.44,.27),new THREE.MeshBasicMaterial({map:screenTexture(['LIBRARY OF','DOROTHY WOLFE','READER 001'])}));card.rotation.x=-Math.PI/2;card.position.set(0,.872,.1);g.add(card);mechanisms.set(o.key,{type:'card',mesh:card,baseY:card.position.y});}
  else if(o.key.startsWith('thread')){rx=rz=0;focusY=1.1;const material=new THREE.MeshBasicMaterial({color:'#ffbddf'});const a=box(g,0,1.1,0,.04,.35,.04,material),b=box(g,0,1.1,0,.04,.35,.04,material);a.rotation.z=.7;b.rotation.z=-.7;threadMeshes.push(g);}
  g.userData.focusY=focusY;if(rx)colliders.push({x:o.x,z:o.y,rx,rz,key:o.key});
 }

 // Rugs and framed openings make the salon and its four wings legible.
 const rugMaterial=mat('#895271'),rugEdge=mat('#efbdd5');
 function rug(x,z,w,d){const group=new THREE.Group();scene.add(group);box(group,x,.008,z,w,.012,d,rugMaterial);for(const side of [-1,1]){box(group,x+side*(w/2-.11),.018,z,.045,.006,d-.16,rugEdge);box(group,x,.018,z+side*(d/2-.11),w-.16,.006,.045,rugEdge)}}
 rug(10.5,11.2,5.4,4.7);rug(10.5,15.8,1.8,4.2);rug(4.5,4.5,3.5,3.2);rug(14.5,4.5,4,3.2);rug(15.5,17,2.4,2.7);
 for(const [x,z,label]of [[4.5,7.5,'01 / WARDROBE'],[14.5,7.5,'02 / READING'],[4.5,14.5,'03 / LETTERS'],[15.5,14.5,'04 / MIRROR']]){const group=new THREE.Group();scene.add(group);for(const side of [-1,1])box(group,x+side*1.52,1.16,z,.10,2.32,.14,light);box(group,x,2.29,z,3.14,.11,.14,light);const sign=new THREE.Mesh(new THREE.PlaneGeometry(1.15,.34),new THREE.MeshBasicMaterial({map:screenTexture([label]),side:THREE.DoubleSide}));sign.position.set(x,2.32,z+.09);group.add(sign)}
 const playerSpirit=new THREE.Group();scene.add(playerSpirit);const spiritMat=new THREE.MeshBasicMaterial({color:'#fff1fa'}),haloMat=new THREE.MeshBasicMaterial({color:'#ffc3e4',transparent:true,opacity:.13,depthWrite:false});
 const sphere=new THREE.Mesh(new THREE.SphereGeometry(.20,12,8),spiritMat);sphere.position.y=1.5;playerSpirit.add(sphere);const halo=new THREE.Mesh(new THREE.SphereGeometry(.245,12,8),haloMat);halo.position.y=1.5;playerSpirit.add(halo);playerSpirit.traverse(o=>o.layers.set(1));
 // Geometric lace screens and pale inlaid light pools; no additional dynamic lights.
 const laceMaterial=new THREE.MeshBasicMaterial({color:'#f9d9eb',transparent:true,opacity:.34,side:THREE.DoubleSide,depthWrite:false});
 const lattice=new THREE.Group();lattice.position.set(17.7,0,4.3);lattice.rotation.y=Math.PI/2;scene.add(lattice);for(const side of [-1,1])box(lattice,side*.65,1.12,0,.055,2.24,.055,light);for(let i=0;i<11;i++){const strip=box(lattice,-.6+i*.12,1.17,0,.016,1.8,.016,laceMaterial);strip.rotation.z=(i%2?1:-1)*.09}for(let j=0;j<9;j++)box(lattice,0,.4+j*.18,0,1.2,.018,.018,laceMaterial);colliders.push({x:17.7,z:4.3,rx:.08,rz:.7,key:'screen'});
 for(const [x,z]of [[14.5,4.1],[10.5,9.7]]){const pool=new THREE.Mesh(new THREE.CircleGeometry(1.0,20),new THREE.MeshBasicMaterial({color:'#ffd9ea',transparent:true,opacity:.09,depthWrite:false}));pool.rotation.x=-Math.PI/2;pool.position.set(x,.034,z);scene.add(pool)}
 const mobile=new THREE.Group();mobile.position.set(14.5,2.7,3.9);scene.add(mobile);for(let i=0;i<3;i++){const x=(i-1)*.35,y=-.1-i*.15;box(mobile,x,y/2,0,.008,Math.abs(y)+.02,.008,light);const shard=new THREE.Mesh(new THREE.OctahedronGeometry(.12,0),new THREE.MeshBasicMaterial({color:i%2?'#ffe9f6':'#cc95b9'}));shard.position.set(x,y-.10,0);mobile.add(shard)}
 const batches=new Map();scene.traverse(o=>{if(!o.isMesh||o.isInstancedMesh||o.geometry!==boxGeometry)return;let p=o;while(p){if(p===playerSpirit||p===mobile||p.userData.key)return;p=p.parent}const key=o.material; if(!batches.has(key))batches.set(key,[]);batches.get(key).push(o)});scene.updateMatrixWorld(true);for(const [material,meshes]of batches){if(meshes.length<2)continue;const batch=new THREE.InstancedMesh(boxGeometry,material,meshes.length);meshes.forEach((mesh,i)=>{batch.setMatrixAt(i,mesh.matrixWorld);mesh.removeFromParent()});scene.add(batch)}
 const atmosphere=buildAtmosphere(scene,map,objects,!!textures.lowPower);
 return {scene,props,colliders,wallMeshes,threadMeshes,wallpaper,paint,light:sun,textures,mirrorSurface,reflectionRibbon,miniMarker,mechanisms,playerSpirit,passagePanel,passageSeam,mobile,...atmosphere};
}
export class ApartmentWorld{
 constructor(canvas,map,objects,touch){
  this.renderer=new THREE.WebGLRenderer({canvas,antialias:false,alpha:false,powerPreference:'low-power'});this.renderer.setPixelRatio(1);this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.camera=new THREE.PerspectiveCamera(74,1,.08,60);this.touch=touch;this.objects=objects;this.ray=new THREE.Raycaster();this.pointer=new THREE.Vector2();this.target=new THREE.Vector3();this.map=map;
  const loader=new THREE.TextureLoader();const wallpaper=loader.load('assets/wallpaper.png'),parquet=loader.load('assets/parquet.png');for(const t of [wallpaper,parquet]){t.colorSpace=THREE.SRGBColorSpace;t.magFilter=THREE.NearestFilter;t.minFilter=THREE.LinearMipmapLinearFilter;t.wrapS=t.wrapT=THREE.RepeatWrapping}parquet.repeat.set(7,7);parquet.magFilter=THREE.LinearFilter;parquet.anisotropy=this.touch?1:Math.min(4,this.renderer.capabilities.getMaxAnisotropy());
  Object.assign(this,buildApartment(map,objects,{wallpaper,parquet,lowPower:touch}));this.resize();this.dream=null;this.lace=null;this.seenThreads=new Set();this.burstStart=null;this.activation=null;this.passageStart=null;this.passageOpen=false;this.lastPlayer=null;this.walkPhase=0;this.walkAmount=0;
 }
 resize(){const ratio=innerWidth/innerHeight,budget=this.touch?100000:360000,w=Math.min(900,Math.max(200,Math.floor(Math.sqrt(budget*ratio)))),h=Math.round(w/ratio);this.renderer.setSize(w,h,false);this.camera.aspect=ratio;this.camera.updateProjectionMatrix()}
 blocked(x,z){return this.colliders.some(c=>!(c.key==='passage'&&this.passageOpen)&&Math.abs(x-c.x)<c.rx+.19&&Math.abs(z-c.z)<c.rz+.19)}
 objectFrom(mesh){while(mesh){if(mesh.userData.skipInteraction)return null;if(mesh.userData.key)return mesh.userData.object;mesh=mesh.parent}return null}
 clearPath(x,z,tx,tz){const distance=Math.hypot(tx-x,tz-z),steps=Math.ceil(distance/.12);for(let i=1;i<steps;i++){const t=i/steps,px=x+(tx-x)*t,pz=z+(tz-z)*t;if(px<20&&(this.map[Math.floor(pz)]?.[Math.floor(px)]!=='0'))return false;if(!this.passageOpen){const c=this.colliders.find(c=>c.key==='passage');if(c&&Math.abs(px-c.x)<c.rx&&Math.abs(pz-c.z)<c.rz)return false}}return true}
 hitAt(x,y){this.pointer.set(x/innerWidth*2-1,-y/innerHeight*2+1);this.ray.setFromCamera(this.pointer,this.camera);this.ray.far=4;const hit=this.ray.intersectObjects(Array.from(this.props.values()).filter(g=>g.visible),true)[0];if(!hit||!this.clearPath(this.camera.position.x,this.camera.position.z,hit.point.x,hit.point.z))return null;const object=this.objectFrom(hit.object);return object?.key==='passage'&&(!this.dream||this.passageOpen)?null:object}
 nearest(player,found){let result=null,min=3.4;const origin=this.camera.position;for(const o of this.objects){if(found.has(o.key)||(o.key==='passage'&&(!this.dream||this.passageOpen)))continue;const g=this.props.get(o.key);if(!g)continue;const dx=o.x-player.x,dz=o.y-player.y,distance=Math.hypot(dx,dz);if(distance>min||distance<.05||(dx*Math.cos(player.a)+dz*Math.sin(player.a))/distance<.65)continue;this.target.set(o.x,g.userData.focusY||1.1,o.y).sub(origin).normalize();this.ray.set(origin,this.target);this.ray.far=4;const hit=this.ray.intersectObjects(Array.from(this.props.values()).filter(g=>g.visible),true)[0];if(hit&&this.objectFrom(hit.object)?.key===o.key&&this.clearPath(origin.x,origin.z,hit.point.x,hit.point.z)){min=distance;result=o}}return result}
 activate(key,time){if(this.activation)this.updateMechanisms(this.activation.time+2000);this.activation={key,time}}
 updateMechanisms(time){const a=this.activation;if(!a)return;const age=(time-a.time)/1000,t=age>.9?Math.max(0,1-(age-.9)/.4):Math.min(1,Math.max(0,age/.42)),ease=t*t*(3-2*t),m=this.mechanisms.get(a.key);if(!m)return;if(m.type==='doors')for(const d of m.doors)d.hinge.rotation.y=d.side*ease*1.02;if(m.type==='book'||m.type==='card'){m.mesh.position.y=m.baseY+ease*.22;m.mesh.rotation.z=-ease*.15}if(m.type==='model')m.mesh.position.y=ease*.13;if(m.type==='dial')m.mesh.rotation.z=ease*Math.PI*.6;if(m.type==='screen')m.material.color.setRGB(1,1-ease*.17,1-ease*.05)}
 openPassage(time){if(this.passageStart===null)this.passageStart=time}
 render(player,found,dream,lace,time,reduced){this.updateMechanisms(time);const distance=this.lastPlayer?Math.hypot(player.x-this.lastPlayer.x,player.y-this.lastPlayer.y):0;this.lastPlayer={x:player.x,y:player.y};const walking=distance>.0005&&distance<.25;this.walkAmount+=(Number(walking)-this.walkAmount)*.22;if(walking)this.walkPhase+=distance*8;const bob=reduced?0:Math.sin(this.walkPhase)*.012*this.walkAmount;this.camera.position.set(player.x,1.55+bob,player.y);this.camera.lookAt(player.x+Math.cos(player.a),1.51+bob,player.y+Math.sin(player.a));this.playerSpirit.position.set(player.x,reduced?0:Math.sin(time*.0012)*.045,player.y);this.playerSpirit.rotation.y=-player.a-Math.PI/2;if(this.mobile&&!reduced)this.mobile.rotation.y=Math.sin(time*.0002)*.22;if(this.passageSeam)this.passageSeam.visible=dream&&!this.passageOpen;if(this.passageStart!==null&&this.passagePanel){const t=reduced?1:Math.min(1,(time-this.passageStart)/1100);this.passagePanel.position.y=t*t*(3-2*t)*2.8;this.passageOpen=t>.9;}this.camera.updateMatrixWorld();if(this.mirrorSurface){const m=this.objects.find(o=>o.key==='mirror');this.mirrorSurface.visible=!!m&&Math.hypot(player.x-m.x,player.y-m.y)<5&&this.clearPath(player.x,player.y,m.x,m.y)}for(const g of this.threadMeshes){g.visible=!found.has(g.userData.key);if(!reduced){g.rotation.y=time*.0007;g.position.y=Math.sin(time*.0017+g.position.x)*.07}}if(this.dream!==dream){this.dream=dream;this.scene.background.set(dream?'#492144':'#1e122c');this.scene.fog.color.copy(this.scene.background);this.light.color.set(dream?'#ff9bcd':'#fff1f5')}if(this.lace!==lace){this.lace=lace;this.wallpaper.map=lace?this.textures.wallpaper:null;this.wallpaper.needsUpdate=true}if(this.miniMarker){this.miniMarker.visible=player.x<20;this.miniMarker.position.x=(player.x-10)*.062;this.miniMarker.position.z=(player.y-10)*.062;this.miniMarker.rotation.y=-player.a-Math.PI/2}if(this.reflectionRibbon&&!reduced){this.reflectionRibbon.rotation.y=time*.00045;this.reflectionRibbon.rotation.z=Math.sin(time*.0007)*.3;this.reflectionRibbon.position.y=1.3+Math.sin(time*.0009)*.1}this.updateAtmosphere(found,time,reduced);this.renderer.render(this.scene,this.camera)}
 updateAtmosphere(found,time,reduced){
  for(const key of found)if(!this.seenThreads.has(key)){this.seenThreads.add(key);const o=this.objects.find(o=>o.key===key);if(o&&!reduced){this.burstOrigin.set(o.x,1.1,o.y);this.burstStart=time}}
  const t=time*.001,position=this.dustGeometry.attributes.position;
  if(!reduced){for(let i=0;i<this.dustSeeds.length;i++){const p=this.dustSeeds[i];position.setXYZ(i,p.x+Math.sin(t*p.speed+p.phase)*.075,p.y+Math.sin(t*p.speed*.7+p.phase)*.12,p.z+Math.cos(t*p.speed*.85+p.phase)*.075)}position.needsUpdate=true}
  this.crtGlow.intensity=reduced?.65:.65+Math.sin(t*.48)*.045;
  const age=this.burstStart===null?3:(time-this.burstStart)/1000;
  this.burst.visible=!reduced&&age>=0&&age<1.8;
  if(this.burst.visible){const p=this.burst.geometry.attributes.position;for(let i=0;i<this.burstVelocities.length;i++){const v=this.burstVelocities[i];p.setXYZ(i,this.burstOrigin.x+v.x*age,this.burstOrigin.y+v.y*age+.06*age,this.burstOrigin.z+v.z*age)}p.needsUpdate=true;this.burst.material.opacity=.6*(1-age/1.8)}
 }
 async replaceProp(key,url){const previous=this.props.get(key);if(!previous)throw new Error('Unknown prop: '+key);const {GLTFLoader}=await import('./vendor/loaders/GLTFLoader.js');const gltf=await new GLTFLoader().loadAsync(url);const replacement=gltf.scene;replacement.position.copy(previous.position);replacement.userData={...previous.userData};replacement.traverse(o=>{if(o.isMesh){const mats=Array.isArray(o.material)?o.material:[o.material];for(const m of mats){m.flatShading=true;if(m.map)m.map.magFilter=THREE.NearestFilter}}});this.scene.add(replacement);this.scene.remove(previous);this.props.set(key,replacement);return replacement}
}

// Seeded random placement: stable between visits, without repeated rings or height bands.
export function buildAtmosphere(scene,map,objects,lowPower=false){
 let seed=284713;const random=()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return ((t^t>>>14)>>>0)/4294967296};
 const stars=[];
 for(const [count,size,opacity]of [[130,.055,.5],[60,.105,.72],[18,.16,.88]]){const positions=[],colors=[];for(let i=0;i<count;i++){const az=random()*Math.PI*2,elevation=.10+random()*.88,radius=36+random()*8,horizontal=radius*Math.sqrt(1-elevation*elevation);positions.push(10+Math.cos(az)*horizontal,2+radius*elevation,10+Math.sin(az)*horizontal);const brightness=.55+random()*.45;colors.push(brightness,brightness*(.73+random()*.2),brightness*(.85+random()*.15))}const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));geometry.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));const points=new THREE.Points(geometry,new THREE.PointsMaterial({size,sizeAttenuation:true,vertexColors:true,transparent:true,opacity,depthWrite:false,fog:false}));scene.add(points);stars.push(points)}
 const cells=[];for(let z=0;z<map.length;z++)for(let x=0;x<map[z].length;x++)if(map[z][x]==='0')cells.push({x,z});
 const dustSeeds=[],positions=[],count=cells.length?(lowPower?45:120):0;
 for(let i=0;i<count;i++){const cell=cells[Math.floor(random()*cells.length)],p={x:cell.x+.2+random()*.6,y:.3+random()*1.45,z:cell.z+.2+random()*.6,phase:random()*Math.PI*2,speed:.12+random()*.24};dustSeeds.push(p);positions.push(p.x,p.y,p.z)}
 const dustGeometry=new THREE.BufferGeometry();dustGeometry.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));dustGeometry.attributes.position.setUsage(THREE.DynamicDrawUsage);const dust=new THREE.Points(dustGeometry,new THREE.PointsMaterial({color:'#ffe5ed',size:.026,transparent:true,opacity:.38,depthWrite:false,sizeAttenuation:true}));dust.frustumCulled=false;scene.add(dust);
 const computer=objects.find(o=>o.key==='terminal');const crtGlow=new THREE.PointLight('#ff93c8',.65,3,2);crtGlow.position.set(computer?.x||10.5,1.24,(computer?.y||8.4)+.55);scene.add(crtGlow);
 const burstVelocities=[];for(let i=0;i<22;i++){const az=random()*Math.PI*2,speed=.09+random()*.15;burstVelocities.push({x:Math.cos(az)*speed,y:(random()-.35)*.20,z:Math.sin(az)*speed})}
 const burstGeometry=new THREE.BufferGeometry();burstGeometry.setAttribute('position',new THREE.Float32BufferAttribute(new Float32Array(66),3));burstGeometry.attributes.position.setUsage(THREE.DynamicDrawUsage);const burst=new THREE.Points(burstGeometry,new THREE.PointsMaterial({color:'#ffc6e5',size:.035,transparent:true,opacity:.6,depthWrite:false}));burst.visible=false;burst.frustumCulled=false;scene.add(burst);
 return {stars,dust,dustGeometry,dustSeeds,crtGlow,burst,burstVelocities,burstOrigin:new THREE.Vector3()};
}
